from __future__ import annotations


def automation_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT — Автоматизация</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#6d8cff}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#07101d,#0b1423);color:var(--text)}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#07101df2;z-index:5}h1,h2,h3{margin:0}.muted{color:var(--muted)}main{padding:24px 28px;max-width:1900px;margin:auto}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{background:#101b2df5;border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:32px;font-weight:800;margin-top:8px}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}button{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 13px;cursor:pointer}button.primary{background:linear-gradient(135deg,#496ee8,#7657de);border-color:transparent}button:disabled{opacity:.55;cursor:wait}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:11px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:var(--muted);font-size:12px}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.pill.ok{background:rgba(57,217,138,.13)}.pill.error{background:rgba(255,97,123,.13)}.pill.running{background:rgba(109,140,255,.16)}.notice{padding:14px;border:1px dashed var(--line);border-radius:10px;background:#0d1828}.two{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;margin-top:18px}.history{max-height:520px;overflow:auto}.event{padding:12px;background:#0d192a;border:1px solid var(--line);border-radius:10px;margin:9px 0}.event-head{display:flex;justify-content:space-between;gap:12px}.small{font-size:12px}.toolbar{display:flex;gap:8px;align-items:center}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:650px){header,main{padding:15px}.grid{grid-template-columns:1fr}table{display:block;overflow:auto}}
</style></head><body><header><div><h1>Scheduling & Automation</h1><div class="muted">1.0.0-rc.6 · автоматический сбор, отчёты и журнал запусков</div></div><div class="toolbar"><button id="refresh">Обновить</button><span id="status" class="muted"></span></div></header><main>
<div class="grid"><div class="card"><div class="muted">Планировщик</div><div id="enabled" class="metric">—</div></div><div class="card"><div class="muted">Задач</div><div id="jobs" class="metric">—</div></div><div class="card"><div class="muted">Выполняется</div><div id="running" class="metric">—</div></div><div class="card"><div class="muted">Последних ошибок</div><div id="failed" class="metric">—</div></div></div>
<div class="two"><section class="card"><h3>Расписание задач</h3><div class="notice muted" style="margin-top:12px">Расписание задаётся через <code>.env</code>. Ручной запуск доступен независимо от расписания. Одновременный повторный запуск одной задачи блокируется.</div><div style="overflow:auto"><table><thead><tr><th>Задача</th><th>Расписание</th><th>Последний запуск</th><th>Статус</th><th></th></tr></thead><tbody id="jobRows"></tbody></table></div></section><section class="card"><h3>Журнал запусков</h3><div id="history" class="history"></div></section></div>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function req(url,opt){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',...(opt||{})});if(!r.ok)throw new Error(await r.text());return r.json()}function when(v){return v?new Date(v).toLocaleString():'ещё не запускалась'}function render(d){$('#enabled').textContent=d.enabled?'включён':'выключен';$('#enabled').className='metric '+(d.enabled?'ok':'warn');$('#jobs').textContent=(d.jobs||[]).length;$('#running').textContent=d.running_jobs||0;$('#failed').textContent=d.failed_jobs||0;$('#failed').className='metric '+((d.failed_jobs||0)>0?'bad':'ok');$('#jobRows').innerHTML=(d.jobs||[]).map(j=>`<tr><td><b>${esc(j.title)}</b><div class="muted small">${esc(j.name)}</div></td><td><code>${esc(j.schedule)}</code><div class="muted small">${j.enabled?'включена':'отключена'}${j.schedule_error?' · '+esc(j.schedule_error):''}</div></td><td>${esc(when(j.last_run_at))}<div class="muted small">${j.last_duration_seconds??'—'} сек. · ${esc(j.last_trigger||'—')}</div></td><td><span class="pill ${j.running?'running':j.last_status==='error'?'error':j.last_status==='ok'?'ok':''}">${j.running?'running':esc(j.last_status||'нет данных')}</span>${j.last_error?`<div class="bad small">${esc(j.last_error)}</div>`:''}</td><td><button class="primary" data-run="${esc(j.name)}" ${j.running?'disabled':''}>Запустить</button></td></tr>`).join('');$('#history').innerHTML=(d.history||[]).map(x=>`<div class="event"><div class="event-head"><b>${esc(x.title||x.job)}</b><span class="pill ${x.status==='ok'?'ok':'error'}">${esc(x.status)}</span></div><div class="muted small">${esc(when(x.finished_at||x.started_at))} · ${esc(x.trigger)} · ${x.duration_seconds??'—'} сек.</div>${x.error?`<div class="bad small">${esc(x.error)}</div>`:''}</div>`).join('')||'<div class="muted">История пока пуста</div>';$('#status').textContent='Часовой пояс: '+d.timezone+' · '+new Date().toLocaleTimeString()}
async function load(){render(await req('/scheduler/status'))}async function run(name,button){button.disabled=true;button.textContent='Запуск…';try{await req('/scheduler/run/'+encodeURIComponent(name),{method:'POST'});await load()}catch(e){alert('Ошибка запуска: '+e.message)}finally{button.disabled=false;button.textContent='Запустить'}}document.addEventListener('click',e=>{const b=e.target.closest('[data-run]');if(b)run(b.dataset.run,b)});$('#refresh').addEventListener('click',()=>load().catch(e=>$('#status').textContent='Ошибка: '+e.message));load().catch(e=>$('#status').textContent='Ошибка: '+e.message);setInterval(()=>load().catch(()=>{}),30000)
</script></body></html>'''
