from __future__ import annotations


def business_architecture_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT Enterprise — Business Architecture Audit</title><style>
:root{color-scheme:dark;--bg:#08101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#07101d,#0b1423);color:var(--text)}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#07101df2;z-index:5}a{color:var(--accent);text-decoration:none}button{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px 14px;cursor:pointer}button:disabled{opacity:.55}main{padding:24px 28px;max-width:1900px;margin:auto}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{background:#101b2df5;border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:34px;font-weight:800;margin-top:8px}.muted{color:var(--muted)}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}.tabs{display:flex;gap:8px;margin:18px 0;flex-wrap:wrap}.tab.active{border-color:var(--accent)}.view{display:none}.view.active{display:block}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.scoregrid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:14px}.score{padding:12px;background:#0d192a;border:1px solid var(--line);border-radius:10px}.rec{padding:14px;border-left:3px solid var(--warn);background:#121f34;border-radius:9px;margin:10px 0}.rec.high,.rec.critical{border-color:var(--bad)}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:var(--muted)}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.notice{padding:14px;border:1px dashed var(--line);border-radius:10px;background:#0d1828}@media(max-width:1100px){.grid,.scoregrid,.two{grid-template-columns:1fr 1fr}}@media(max-width:650px){header,main{padding:15px}.grid,.scoregrid,.two{grid-template-columns:1fr}}
</style></head><body><header><div><h1>AI-BIT Enterprise — Business Architecture Audit</h1><div class="muted">1.0.0-rc.1 · процессы, CRM-воронки и документооборот</div></div><div><a href="/executive">Executive</a> · <a href="/operations">Операции</a> · <a href="/processes">Process Mining</a> <button id="collect">Запустить аудит</button><div id="status" class="muted"></div></div></header><main>
<div class="grid"><div class="card"><div class="muted">Enterprise Health</div><div id="health" class="metric">—</div></div><div class="card"><div class="muted">Бизнес-процессы</div><div id="bpScore" class="metric">—</div></div><div class="card"><div class="muted">CRM-воронки</div><div id="crmScore" class="metric">—</div></div><div class="card"><div class="muted">Документооборот</div><div id="docScore" class="metric">—</div></div></div>
<div class="tabs"><button class="tab active" data-view="summary">Сводка</button><button class="tab" data-view="business_processes">Бизнес-процессы</button><button class="tab" data-view="crm">CRM-воронки</button><button class="tab" data-view="documents">Документооборот</button><button class="tab" data-view="recommendations">Рекомендации</button></div>
<div id="summary" class="view active"><div class="two"><section class="card"><h3>Статус контуров</h3><div id="domainSummary"></div></section><section class="card"><h3>Методика</h3><p id="methodology" class="muted"></p><div class="notice">Оценка не считается подтверждённой без REST/Browser evidence. Недоступный метод отображается как partial или insufficient_data.</div></section></div></div>
<div id="business_processes" class="view"><section class="card"><h3>Аудит бизнес-процессов</h3><div id="bpDetails"></div></section></div>
<div id="crm" class="view"><section class="card"><h3>Аудит CRM-воронок</h3><div id="crmDetails"></div></section></div>
<div id="documents" class="view"><section class="card"><h3>Аудит документооборота</h3><div id="docDetails"></div></section></div>
<div id="recommendations" class="view"><section class="card"><h3>Приоритетные рекомендации</h3><div id="recRows"></div></section></div>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function json(url,opt){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',...(opt||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
function cls(n){return n>=70?'ok':n>=45?'warn':'bad'}function scores(x){return `<div class="scoregrid">${Object.entries(x.scores||{}).map(([k,v])=>`<div class="score"><div class="muted">${esc(k)}</div><b class="${cls(v)}">${v}%</b></div>`).join('')}</div>`}function recs(rows){return (rows||[]).map(r=>`<div class="rec ${esc(r.severity)}"><b>${esc(r.title)}</b><p>${esc(r.finding)}</p><div class="muted">Что делать: ${esc(r.action)}</div><div class="muted">Evidence: ${esc((r.evidence||[]).join(', '))}</div></div>`).join('')||'<div class="muted">Рекомендаций нет</div>'}
function domain(title,x){return `<div class="card" style="margin-top:12px"><div style="display:flex;justify-content:space-between"><b>${esc(title)}</b><span class="pill">${esc(x.status)} · ${esc(x.evidence_status)}</span></div><div class="metric ${cls(x.score)}">${x.score}%</div>${scores(x)}<pre class="muted" style="white-space:pre-wrap">${esc(JSON.stringify(x.summary||{},null,2))}</pre></div>`}
function render(d){const dom=d.domains||{};$('#health').textContent=(d.enterprise_health??0)+'%';$('#health').className='metric '+cls(d.enterprise_health??0);$('#bpScore').textContent=(dom.business_processes?.score??0)+'%';$('#crmScore').textContent=(dom.crm?.score??0)+'%';$('#docScore').textContent=(dom.documents?.score??0)+'%';$('#domainSummary').innerHTML=domain('Бизнес-процессы',dom.business_processes||{})+domain('CRM-воронки',dom.crm||{})+domain('Документооборот',dom.documents||{});$('#bpDetails').innerHTML=domain('Бизнес-процессы',dom.business_processes||{})+recs(dom.business_processes?.recommendations);$('#crmDetails').innerHTML=domain('CRM-воронки',dom.crm||{})+recs(dom.crm?.recommendations);$('#docDetails').innerHTML=domain('Документооборот',dom.documents||{})+recs(dom.documents?.recommendations);$('#recRows').innerHTML=recs(d.recommendations);$('#methodology').textContent=d.methodology||'';$('#status').textContent='Обновлено: '+new Date(d.generated_at).toLocaleString()}
async function load(){render(await json('/business-architecture/latest'))}$('#collect').addEventListener('click',async()=>{const b=$('#collect');b.disabled=true;b.textContent='Аудит…';$('#status').textContent='Получаю данные из Bitrix24…';try{render(await json('/business-architecture/collect',{method:'POST'}))}catch(e){$('#status').textContent='Ошибка: '+e.message}finally{b.disabled=false;b.textContent='Запустить аудит'}});$('.tabs').addEventListener('click',e=>{if(!e.target.dataset.view)return;document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.view).classList.add('active')});load().catch(e=>$('#status').textContent='Сначала нажмите «Запустить аудит»: '+e.message)
</script></body></html>'''
