from __future__ import annotations


def dashboard_html() -> str:
    return r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI-BIT — аудит внедрения</title>
<style>
:root{color-scheme:dark;--bg:#08101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff;--purple:#aa8cff}
*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#08101d,#0c1424);color:var(--text)}a{color:var(--accent);text-decoration:none}
header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:16px;align-items:center;position:sticky;top:0;background:rgba(8,16,29,.95);z-index:5}h1,h2,h3,h4{margin:0}h1{font-size:24px}.muted{color:var(--muted)}
button,select{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 12px}button{cursor:pointer}button:disabled{opacity:.55;cursor:wait}
main{padding:24px 28px;max-width:1900px;margin:auto}.grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.card{background:rgba(16,27,45,.97);border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:30px;font-weight:750;margin-top:8px}.score{font-size:46px;color:var(--accent)}section{margin-top:18px}.two{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.ok,.used,.detected{color:var(--ok)}.warn,.needs_configuration,.partial,.redirected,.at_risk{color:var(--warn)}.bad,.blocked,.not_detected,.denied,.error,.not_found,.high{color:var(--bad)}
.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tab.active{border-color:var(--accent)}.view{display:none}.view.active{display:block}.empty{padding:28px;text-align:center;color:var(--muted)}
.module{display:grid;grid-template-columns:1.1fr .55fr 1.7fr;gap:14px;padding:15px 0;border-bottom:1px solid var(--line)}.audit-card{padding:18px;margin:12px 0;background:#0d1829;border:1px solid var(--line);border-radius:12px}.audit-head{display:flex;justify-content:space-between;gap:12px}.rec{padding:12px 14px;border-left:3px solid var(--warn);background:#121f34;border-radius:8px;margin:9px 0}.rec.high{border-color:var(--bad)}.rec.low{border-color:var(--accent)}ul{margin:8px 0 0;padding-left:20px}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted)}.scroll{overflow:auto;max-height:700px}.bar{height:9px;background:#202f49;border-radius:8px;overflow:hidden}.bar span{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--purple))}.node{padding:7px 10px;margin:4px 0;border-left:2px solid var(--line);background:#0e192a;border-radius:6px}#status{text-align:right;min-height:18px;margin-top:5px}
@media(max-width:1100px){.grid{grid-template-columns:repeat(2,1fr)}.two,.three{grid-template-columns:1fr}}@media(max-width:650px){header,main{padding:15px}.grid{grid-template-columns:1fr}.module{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>AI-BIT — аудит внедрения</h1><div class="muted">Deep Audit 0.8.0: модули, страницы, риски и план действий</div></div><div><div><select id="audit"></select> <button id="refresh">Обновить</button></div><div id="status" class="muted"></div></div></header>
<main>
<div class="grid">
 <div class="card"><div class="muted">Implementation score</div><div class="metric score" id="score">—</div><div id="maturity" class="muted"></div></div>
 <div class="card"><div class="muted">Используется</div><div class="metric used" id="used">—</div></div>
 <div class="card"><div class="muted">Проблемных страниц</div><div class="metric bad" id="problemPages">—</div></div>
 <div class="card"><div class="muted">Страниц с рекомендациями</div><div class="metric warn" id="recommendedPages">—</div></div>
 <div class="card"><div class="muted">Приоритетных действий</div><div class="metric bad" id="highActions">—</div></div>
</div>
<div class="tabs">
 <button class="tab active" data-view="overview">Обзор</button><button class="tab" data-view="deepModules">Глубокий аудит модулей</button><button class="tab" data-view="pageAudit">Аудит страниц</button><button class="tab" data-view="actionPlan">План действий</button><button class="tab" data-view="map">Карта портала</button><button class="tab" data-view="changes">Изменения</button>
</div>
<div id="overview" class="view active"><section class="two"><div class="card"><h3>Что уже используется</h3><div id="usedList"></div></div><div class="card"><h3>Что требует внимания</h3><div id="attention"></div></div></section><section class="two"><div class="card"><h3>Покрытие по разделам</h3><div id="sectionBars"></div></div><div class="card"><h3>Методика</h3><p id="methodology" class="muted"></p></div></section></div>
<div id="deepModules" class="view"><section class="card"><h3>Аудит модулей</h3><div id="deepModuleList"></div></section></div>
<div id="pageAudit" class="view"><section class="card"><h3>Рекомендации по каждой странице</h3><div class="scroll"><table><thead><tr><th>Риск</th><th>Раздел / страница</th><th>Evidence</th><th>Рекомендации</th></tr></thead><tbody id="pageAuditRows"></tbody></table></div></section></div>
<div id="actionPlan" class="view"><section class="two"><div class="card"><h3>Приоритетный план</h3><div id="actionList"></div></div><div class="card"><h3>Важно</h3><p class="muted">Версия 0.8.0 строит рекомендации по browser evidence. Детальная аналитика воронок, роботов, задач и сотрудников появится после объединения с REST snapshot в 0.9.0.</p></div></section></div>
<div id="map" class="view"><section class="two"><div class="card"><h3>Карта портала</h3><div id="tree"></div></div><div class="card"><h3>Все страницы</h3><div class="scroll"><table><thead><tr><th>Раздел</th><th>Страница</th><th>Статус</th></tr></thead><tbody id="pages"></tbody></table></div></div></section></div>
<div id="changes" class="view"><section class="card"><h3>Изменения с предыдущего аудита</h3><div id="diff"></div></section></div>
</main>
<script>
const $=s=>document.querySelector(s);let history=[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getJSON(url){const sep=url.includes('?')?'&':'?';const r=await fetch(url+sep+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function moduleCard(m){return `<div class="module"><div><b>${esc(m.title)}</b><div class="muted">${esc(m.why)}</div></div><div><span class="pill ${esc(m.state)}">${esc(m.state)}</span></div><div>${m.pages} стр.${(m.sample_pages||[]).slice(0,3).map(p=>`<div><a target="_blank" href="${esc(p.url)}">${esc(p.title||p.url)}</a></div>`).join('')}</div></div>`}
function renderAssessment(a){$('#score').textContent=a.implementation_score==null?'—':a.implementation_score+'%';$('#maturity').textContent=a.maturity||'';$('#used').textContent=a.counts?.used??0;$('#usedList').innerHTML=(a.used||[]).map(moduleCard).join('')||'<div class="empty">Не обнаружено</div>';$('#attention').innerHTML=[...(a.blocked||[]),...(a.needs_configuration||[]),...(a.not_detected||[])].map(moduleCard).join('')||'<div class="empty">Критичных пробелов нет</div>'}
function renderDeep(d){$('#problemPages').textContent=d.summary?.problem_pages??0;$('#recommendedPages').textContent=d.summary?.pages_with_recommendations??0;$('#highActions').textContent=d.summary?.high_priority_actions??0;$('#methodology').textContent=d.methodology||'';$('#deepModuleList').innerHTML=(d.modules||[]).map(m=>`<div class="audit-card"><div class="audit-head"><div><h3>${esc(m.title)}</h3><div class="muted">${esc(m.goal)}</div></div><div><span class="pill ${esc(m.maturity)}">${esc(m.maturity)}</span> <b>${m.score}%</b><div class="muted">${m.pages} стр. · проблемных ${m.problem_pages}</div></div></div><div class="two" style="margin-top:14px"><div><b>Что проверять</b><ul>${(m.checks||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><b>Рекомендации</b><ul>${(m.recommendations||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></div>`).join('');$('#pageAuditRows').innerHTML=(d.pages||[]).map(p=>`<tr><td><span class="pill ${esc(p.risk)}">${esc(p.risk)}</span><br><span class="muted">${esc(p.status)}</span></td><td><b>${esc(p.section)}</b><br><a target="_blank" href="${esc(p.url)}">${esc(p.title)}</a></td><td><span class="muted">Ссылок: ${p.evidence?.link_count??0}<br>Глубина: ${p.evidence?.depth??0}</span></td><td>${(p.recommendations||[]).length?`<ul>${p.recommendations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<span class="muted">Критичных замечаний нет</span>'}</td></tr>`).join('');$('#actionList').innerHTML=(d.action_plan||[]).map(x=>`<div class="rec ${esc(x.priority)}"><b>${esc(x.title)}</b> <span class="pill ${esc(x.priority)}">${esc(x.priority)}</span><p>${esc(x.action)}</p><div class="muted">Ожидаемый эффект: ${esc(x.expected_effect)}</div></div>`).join('')||'<div class="empty">Приоритетных действий нет</div>'}
function renderSections(sections){const max=Math.max(1,...Object.values(sections));$('#sectionBars').innerHTML=Object.entries(sections).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="margin:12px 0"><div style="display:flex;justify-content:space-between"><span>${esc(k)}</span><b>${v}</b></div><div class="bar"><span style="width:${Math.round(v/max*100)}%"></span></div></div>`).join('')}
function renderNodes(nodes){$('#pages').innerHTML=nodes.map(n=>`<tr><td>${esc(n.section)}</td><td><a href="${esc(n.url)}" target="_blank">${esc(n.title||n.url)}</a></td><td><span class="pill ${esc(n.status)}">${esc(n.status)}</span></td></tr>`).join('');$('#tree').innerHTML=[...nodes].sort((a,b)=>(a.depth??0)-(b.depth??0)).map(n=>`<div class="node" style="margin-left:${Math.min(6,n.depth||0)*18}px"><span class="muted">${esc(n.section)}</span> · <a href="${esc(n.url)}" target="_blank">${esc(n.title||n.url)}</a></div>`).join('')}
async function renderDiff(id){const idx=history.findIndex(x=>x.id===id);if(idx<0||idx===history.length-1){$('#diff').innerHTML='<div class="empty">Нет предыдущего аудита</div>';return}const d=await getJSON(`/crawl/diff?before=${encodeURIComponent(history[idx+1].id)}&after=${encodeURIComponent(id)}`);$('#diff').innerHTML=`<div class="three"><div class="card"><b class="ok">+${d.summary.added}</b><div class="muted">добавлено</div></div><div class="card"><b class="bad">-${d.summary.removed}</b><div class="muted">удалено</div></div><div class="card"><b>${d.summary.changed}</b><div class="muted">изменено</div></div></div>`}
async function loadAudit(id){const [data,a,d]=await Promise.all([getJSON('/crawl/history/'+encodeURIComponent(id)),getJSON('/crawl/assessment/'+encodeURIComponent(id)),getJSON('/crawl/deep-audit/'+encodeURIComponent(id))]);renderAssessment(a);renderDeep(d);renderSections(data.summary?.sections||{});renderNodes(data.nodes||[]);await renderDiff(id);$('#status').textContent=`Загружено: ${data.summary?.visited??0} стр. · Deep Audit ${d.version||''}`}
async function loadHistory(preferred){history=await getJSON('/crawl/history');if(!history.length)throw new Error('Нет crawl-запусков');$('#audit').innerHTML=history.map(x=>`<option value="${esc(x.id)}">${esc(x.created_at)} — ${x.summary?.visited??0} стр.</option>`).join('');const id=preferred&&history.some(x=>x.id===preferred)?preferred:history[0].id;$('#audit').value=id;await loadAudit(id)}
$('.tabs').addEventListener('click',e=>{if(!e.target.dataset.view)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.view).classList.add('active')});$('#audit').addEventListener('change',e=>loadAudit(e.target.value).catch(err=>$('#status').textContent='Ошибка: '+err.message));$('#refresh').addEventListener('click',async()=>{const b=$('#refresh'),id=$('#audit').value;b.disabled=true;b.textContent='Обновление…';try{await loadHistory(id)}catch(e){$('#status').textContent='Ошибка: '+e.message}finally{b.disabled=false;b.textContent='Обновить'}});loadHistory().catch(e=>{$('#status').textContent='Ошибка загрузки';document.querySelector('main').innerHTML='<div class="empty">'+esc(e.message)+'</div>'});
</script></body></html>'''
