from __future__ import annotations


def _shell(title: str, subtitle: str, body_js: str) -> str:
    return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — AI-BIT</title><style>
:root{{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--accent:#6d8cff;--ok:#35d08a;--warn:#ffbd4a;--bad:#ff5d78}}*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 80% 0,rgba(109,140,255,.14),transparent 30%),var(--bg);color:var(--text);font:14px/1.5 Inter,Segoe UI,Arial,sans-serif}}main{{max-width:1280px;margin:auto;padding:26px 28px 90px}}header{{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:20px}}h1{{margin:0;font-size:28px}}h2{{font-size:18px;margin:0 0 12px}}p{{color:var(--muted)}}a{{color:#9db5ff}}.nav{{display:flex;gap:8px;flex-wrap:wrap}}.btn{{display:inline-block;padding:9px 12px;border-radius:10px;border:1px solid var(--line);background:var(--panel);text-decoration:none;color:var(--text)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}}.card,.section{{background:rgba(16,27,45,.84);border:1px solid var(--line);border-radius:15px;padding:17px}}.section{{margin-bottom:14px}}.value{{font-size:29px;font-weight:800;margin-top:6px}}.label,.muted{{color:var(--muted)}}.row{{display:grid;grid-template-columns:1fr auto;gap:12px;padding:11px 0;border-bottom:1px solid rgba(40,57,86,.65)}}.row:last-child{{border:0}}.bar{{height:7px;background:#1b2b44;border-radius:99px;overflow:hidden;margin-top:7px}}.bar i{{display:block;height:100%;background:linear-gradient(90deg,var(--bad),var(--warn),var(--ok))}}.ok{{color:var(--ok)}}.warn{{color:var(--warn)}}.bad{{color:var(--bad)}}.empty{{padding:20px;color:var(--muted)}}details{{margin-top:10px;border:1px solid var(--line);border-radius:12px;padding:12px}}summary{{cursor:pointer;font-weight:700}}@media(max-width:900px){{.grid{{grid-template-columns:repeat(2,1fr)}}}}@media(max-width:600px){{main{{padding:18px}}header{{display:block}}.grid{{grid-template-columns:1fr}}}}
</style></head><body><main><header><div><h1>{title}</h1><p>{subtitle}</p><div id="updated" class="muted">Загрузка данных…</div></div><nav class="nav"><a class="btn" href="/#management">Сводка руководителя</a><a class="btn" href="/digital-passport">Цифровой паспорт</a><a class="btn" href="/process-optimizer">Процессы</a><a class="btn" href="/ai-cio">AI CIO</a><a class="btn" href="/transformation-roadmap">Roadmap</a><a class="btn" href="/risk-forecast">Риски</a><a class="btn" href="/business-value">Экономика</a></nav></header><div id="content"><div class="empty">Формируется представление…</div></div><script>
const $=s=>document.querySelector(s);const esc=v=>{{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}};const num=v=>new Intl.NumberFormat('ru-RU',{{maximumFractionDigits:1}}).format(Number(v||0));const money=v=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(v||0)))+' ₸';const level=v=>Number(v)>=75?'ok':Number(v)>=55?'warn':'bad';
async function load(){{try{{const r=await fetch('/executive-intelligence/latest');const d=await r.json();if(!r.ok)throw new Error(d.detail||'Ошибка');render(d);$('#updated').textContent='Снимок: '+new Date(d.generated_at).toLocaleString('ru-RU')}}catch(e){{$('#content').innerHTML='<div class="section bad">Не удалось загрузить данные: '+esc(e.message)+'</div>'}}}}
{body_js}
load();
</script></main></body></html>'''


def digital_passport_html() -> str:
    js = r'''function render(d){const k=(d.executive_kpi||{}).kpis||[],dims=Object.values(d.dimensions||{}),ref=d.reference_audit||{},opt=d.process_optimizer||{},src=d.source_summary||{};const lookup=n=>k.find(x=>String(x.title||'').toLowerCase().includes(n));const rows=[['CRM',lookup('crm')?.score||dims.find(x=>String(x.title||'').toLowerCase().includes('crm'))?.score],['Документооборот',lookup('документооборот')?.score],['Автоматизация',lookup('автоматизац')?.score],['Бизнес-процессы',opt.overall_score],['Исполнительская дисциплина',lookup('исполнитель')?.score],['Управленческая дисциплина',lookup('управлен')?.score],['Эталонная модель',ref.coverage],['Использование системы',lookup('использован')?.score]];const overall=(d.digital_maturity||{}).score||0;$('#content').innerHTML='<div class="grid"><div class="card"><div class="label">Общий индекс</div><div class="value '+level(overall)+'">'+esc(num(overall))+'</div><div class="muted">из 100</div></div><div class="card"><div class="label">Покрытие модели</div><div class="value '+level(ref.coverage)+'">'+esc(num(ref.coverage))+'%</div></div><div class="card"><div class="label">Просрочка</div><div class="value bad">'+esc(num(src.overdue_rate))+'%</div></div><div class="card"><div class="label">Без срока</div><div class="value warn">'+esc(src.without_deadline||0)+'</div></div></div><section class="section" style="margin-top:14px"><h2>Цифровой паспорт Bitrix24</h2>'+rows.map(x=>'<div class="row"><div><b>'+esc(x[0])+'</b><div class="bar"><i style="width:'+Math.max(0,Math.min(100,Number(x[1]||0)))+'%"></i></div></div><strong class="'+level(x[1])+'">'+esc(x[1]==null?'нет данных':num(x[1]))+'</strong></div>').join('')+'</section>'}'''
    return _shell('Цифровой паспорт Bitrix24', 'Единый экран зрелости, использования и управляемости системы.', js)


def process_optimizer_html() -> str:
    js = r'''function render(d){const o=d.process_optimizer||{},s=o.summary||{},items=o.processes||[],recs=o.top_recommendations||[];$('#content').innerHTML='<div class="grid"><div class="card"><div class="label">Process Score</div><div class="value '+level(o.overall_score)+'">'+esc(num(o.overall_score))+'</div></div><div class="card"><div class="label">Проверено</div><div class="value">'+esc(s.processes_analyzed||0)+'</div></div><div class="card"><div class="label">Можно улучшить</div><div class="value warn">'+esc(s.improvable||0)+'</div></div><div class="card"><div class="label">Переработать</div><div class="value bad">'+esc(s.redesign||0)+'</div></div></div><section class="section" style="margin-top:14px"><h2>Рейтинг процессов</h2>'+items.slice(0,25).map(x=>'<div class="row"><div><b>'+esc(x.name)+'</b><div class="muted">запусков '+esc((x.metrics||{}).runs||0)+' · рекомендаций '+esc((x.recommendations||[]).length)+'</div></div><strong class="'+level(x.score)+'">'+esc(num(x.score))+'</strong></div>').join('')+'</section><section class="section"><h2>Приоритетные рекомендации</h2>'+recs.map((x,i)=>'<details><summary>'+(i+1)+'. '+esc(x.process)+'</summary><p><b>Проблема:</b> '+esc(x.problem)+'</p><p><b>Решение:</b> '+esc(x.recommendation)+'</p><p><b>Эффект:</b> '+esc(x.expected_effect)+'</p></details>').join('')+'</section>'}'''
    return _shell('AI Process Optimizer', 'Подробный анализ повторяющихся операций, маршрутов, узких мест и кандидатов на автоматизацию.', js)


def ai_cio_html() -> str:
    js = r'''function render(d){const c=d.ai_cio||{},items=c.recommendations||[];$('#content').innerHTML='<section class="section"><h2>Что бы сделал CIO в ближайшие 90 дней</h2>'+items.map(x=>'<details open><summary>№'+esc(x.rank)+' · '+esc(x.title)+'</summary><p><b>Почему:</b> '+esc(x.why)+'</p><p><b>Решение:</b> '+esc(x.decision)+'</p><div class="muted">Срок: '+esc(x.period)+' · Ответственный: '+esc(x.owner_role)+' · Уверенность '+esc(x.confidence)+'%</div></details>').join('')+'<p class="muted">'+esc(c.principle||'')+'</p></section>'}'''
    return _shell('AI CIO', 'Приоритетные управленческие решения, сформированные по подтверждённым отклонениям.', js)


def roadmap_html() -> str:
    js = r'''function render(d){const r=d.transformation_roadmap||{},ph=r.phases||[];$('#content').innerHTML=ph.map(p=>'<section class="section"><h2>'+esc(p.title)+' · '+esc(p.period)+'</h2>'+((p.items||[]).map(x=>'<details open><summary>'+esc(x.title)+'</summary><p>'+esc(x.action||'')+'</p><div class="muted">Ответственный: '+esc(x.owner_role||'не назначен')+' · Уверенность '+esc(x.confidence||0)+'%</div></details>').join('')||'<div class="empty">Действия не сформированы.</div>')+'</section>').join('')||'<div class="empty">Дорожная карта отсутствует.</div>'}'''
    return _shell('Дорожная карта трансформации', 'План изменений по этапам, срокам и ответственным ролям.', js)


def risk_forecast_html() -> str:
    js = r'''function render(d){const f=d.risk_forecast||{},items=f.forecasts||[];$('#content').innerHTML='<section class="section"><h2>Доказательный прогноз</h2>'+(f.status==='ok'?items.map(x=>'<div class="row"><div><b>'+esc(x.title)+'</b><div class="muted">текущее '+esc(num(x.current))+esc(x.unit||'')+' → прогноз '+esc(num(x.forecast_two_periods))+esc(x.unit||'')+'</div></div><strong class="'+(x.direction==='worsening'?'bad':x.direction==='improving'?'ok':'warn')+'">'+esc(x.direction==='worsening'?'ухудшение':x.direction==='improving'?'улучшение':'стабильно')+'</strong></div>').join(''):'<div class="empty">Для прогноза требуется минимум 3 исторических снимка. Доступно: '+esc(f.available_snapshots||0)+'.</div>')+'<p class="muted">'+esc(f.warning||'')+'</p></section>'}'''
    return _shell('Прогноз рисков', 'Прогноз строится только по накопленной динамике и не подменяется предположениями.', js)


def business_value_html() -> str:
    js = r'''function render(d){const b=d.business_value||{},parts=[['Автоматизация операций',b.labor],['Бумага, печать и архив',b.paper],['Потери от просрочки',b.overdue_losses],['Задачи без срока',b.no_deadline_losses],['Время руководителей',b.management_time],['Поиск документов',b.document_search]];const total=b.total||{};$('#content').innerHTML='<div class="grid"><div class="card"><div class="label">Совокупный эффект</div><div class="value ok">'+esc(money(total.annual_saving_kzt))+'</div><div class="muted">в год</div></div><div class="card"><div class="label">Экономия времени</div><div class="value">'+esc(num(total.annual_hours))+'</div><div class="muted">часов в год</div></div><div class="card"><div class="label">Стоимость часа</div><div class="value">'+esc(money((b.labor||{}).hourly_rate_kzt))+'</div></div><div class="card"><div class="label">Модель</div><div class="value" style="font-size:18px">Консервативная</div></div></div><section class="section" style="margin-top:14px"><h2>Состав бизнес-эффекта</h2>'+parts.map(x=>'<div class="row"><div><b>'+esc(x[0])+'</b><div class="muted">'+esc(num((x[1]||{}).annual_hours))+' ч/год</div></div><strong>'+esc(money((x[1]||{}).annual_saving_kzt))+'</strong></div>').join('')+'</section><section class="section"><h2>Отдельные управленческие эффекты</h2><div class="row"><span>Ускорение согласований</span><strong>'+esc((b.approvals||{}).expected_acceleration_percent||0)+'%</strong></div><div class="row"><span>Неиспользуемый потенциал</span><strong>'+esc(money((b.unused_potential||{}).indicative_value_kzt))+'</strong></div></section>'}'''
    return _shell('Бизнес-эффект внедрения', 'Прозрачная экономика автоматизации с раздельными формулами и без двойного счёта.', js)
