from __future__ import annotations

from pathlib import Path

DASH_PATH = Path('/app/management_report_dashboard.py')
APP_PATH = Path('/app/app.py')
ADMIN_PATH = Path('/app/admin_dashboard.py')
EXEC_PATH = Path('/app/executive_intelligence.py')
REF_PATH = Path('/app/reference_model.py')

DASHBOARD = r'''from __future__ import annotations


def management_report_dashboard_html() -> str:
    return r"""<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Сводка руководителя</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#35d08a;--warn:#ffbd4a;--bad:#ff5d78}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Segoe UI,Arial,sans-serif}main{max-width:1380px;margin:auto;padding:24px 28px 70px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.hero h1{margin:0;font-size:28px}.muted{color:var(--muted)}button,a.btn{border:1px solid var(--line);background:var(--panel);color:var(--text);padding:9px 12px;border-radius:10px;cursor:pointer;text-decoration:none}.summary{display:grid;grid-template-columns:1.35fr repeat(3,1fr);gap:12px;margin:18px 0}.card,.section{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:18px}.score{font-size:50px;font-weight:800}.value{font-size:27px;font-weight:750}.label{color:var(--muted);font-size:12px}.layout{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.section{margin-bottom:14px}.section h2{margin:0 0 12px;font-size:17px}.issue{padding:12px 0;border-bottom:1px solid var(--line)}.issue:last-child{border:0}.issue h3{margin:0 0 4px}.issue p{margin:3px 0;color:var(--muted)}.bad{color:var(--bad)}.warn{color:var(--warn)}.ok{color:var(--ok)}.decision{padding:12px;margin:8px 0;border:1px solid rgba(109,140,255,.35);border-radius:11px}.row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.roi{display:grid;grid-template-columns:1fr 1fr;gap:10px}.roi div{padding:13px;border:1px solid rgba(53,208,138,.3);border-radius:12px}.roi strong{font-size:22px;color:var(--ok)}details{border:1px solid var(--line);border-radius:12px;padding:12px;margin-top:8px}summary{cursor:pointer;font-weight:700}.status{font-size:12px;color:var(--muted);margin-top:7px}.banner{padding:10px 12px;border-radius:10px;margin:12px 0;background:rgba(53,208,138,.08);border:1px solid rgba(53,208,138,.25)}@media(max-width:1000px){.summary{grid-template-columns:1fr 1fr}.layout{grid-template-columns:1fr}}@media(max-width:650px){main{padding:16px}.hero{display:block}.summary{grid-template-columns:1fr}.roi{grid-template-columns:1fr}}
</style></head><body><main><div class="hero"><div><h1>Сводка руководителя</h1><div class="muted">Готовая управленческая картина без технических терминов. Groq не требуется для отображения страницы.</div><div class="status" id="updated">Загрузка последней готовой сводки…</div></div><div><button id="refresh">Обновить данные</button> <a class="btn" href="/executive-intelligence" target="_blank">Открыть аналитику</a></div></div><div id="banner" class="banner">Используется встроенная аналитическая модель AI-BIT.</div><div id="content"><div class="section muted">Загружаются последние подтверждённые данные…</div></div><details><summary>Подробный отчёт и история</summary><p class="muted">Подробный PDF может использовать Groq. Основная сводка от него не зависит.</p><button id="generate">Сформировать подробный PDF</button><div id="reportStatus" class="status"></div></details></main><script>
const $=s=>document.querySelector(s);const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};const num=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(Number(v||0));const money=v=>v==null?'не рассчитано':new Intl.NumberFormat('ru-RU').format(Math.round(v))+' ₸';
function tone(v){return Number(v)<55?'bad':Number(v)<70?'warn':'ok'}
function decisions(d){const out=[];for(const r of (d.risks||[])){const t=String(r.title||'').toLowerCase();if(t.includes('срок')&&!out.some(x=>x[0].includes('срок')))out.push(['Утвердить обязательные сроки','Сделать срок обязательным и включить эскалацию просрочки.']);else if(t.includes('crm'))out.push(['Утвердить правила ведения CRM','Закрепить обязательные поля, следующее действие и контроль качества данных.']);else if(t.includes('целевой модели'))out.push(['Утвердить план закрытия цифровых разрывов','Назначить владельцев и приоритеты по отсутствующим возможностям.']);else if(t.includes('документооборот'))out.push(['Назначить владельца документооборота','Утвердить единые маршруты, сроки и ответственность.']);if(out.length>=3)break}return out}
function evidence(x){const e=x.evidence_audit||{},sources=e.checked_sources||[];return '<details><summary>Показать доказательства</summary><p>'+esc(e.rationale||'Обоснование сформировано по доступным системным данным.')+'</p>'+sources.map(s=>'<div class="row"><span>'+esc(s.title||s.id)+'</span><b class="'+(s.available?(s.positive?'ok':'warn'):'bad')+'">'+(s.available?(s.positive?'подтверждено':'не найдено'):'недоступно')+'</b></div>').join('')+'</details>'}
function render(d){const m=d.digital_maturity||{},s=d.source_summary||{},roi=d.roi||{},ref=d.reference_audit||{},rs=ref.summary||{},risks=(d.risks||[]).slice(0,5),gaps=(ref.critical_gaps||[]).filter(x=>x.required!==false).slice(0,6),decs=decisions(d),deps=(d.department_rating||[]).filter(x=>Number(x.open||0)>=3||Number(x.score||0)<70).slice(0,5);let h='<div class="summary"><div class="card"><div class="label">Цифровая зрелость</div><div class="score '+tone(m.score)+'">'+num(m.score)+'</div><div class="muted">из 100 · '+esc(m.level||'нет оценки')+'</div></div><div class="card"><div class="label">Просрочка</div><div class="value bad">'+num(s.overdue_rate)+'%</div></div><div class="card"><div class="label">Задачи без срока</div><div class="value warn">'+esc(s.without_deadline||0)+'</div></div><div class="card"><div class="label">Покрытие эталона</div><div class="value '+tone(ref.coverage)+'">'+num(ref.coverage)+'%</div><div class="muted">нет: '+esc(rs.missing||0)+' · проверить: '+esc(rs.unknown||0)+'</div></div></div>';
h+='<div class="layout"><div><section class="section"><h2>Что требует внимания сейчас</h2>'+(risks.length?risks.map(r=>'<div class="issue"><h3>'+esc(r.title)+'</h3><p>'+esc(r.fact||'')+'</p><p>Последствие: '+esc(r.impact||'')+'</p></div>').join(''):'<div class="muted">Критичных рисков не выявлено.</div>')+'</section><section class="section"><h2>Разрывы относительно эталонной модели</h2>'+(gaps.length?gaps.map(x=>'<div class="issue"><h3>'+esc(x.title)+'</h3><p><b class="bad">Не найдено подтверждений</b> · уверенность '+Math.round(Number(x.confidence||0)*100)+'%</p>'+((x.methodology||{}).recommendation?'<p>Рекомендация: '+esc(x.methodology.recommendation)+'</p>':'')+evidence(x)+'</div>').join(''):'<div class="muted">Обязательных подтверждённых разрывов не найдено.</div>')+'</section></div><div><section class="section"><h2>Что необходимо решить руководству</h2>'+(decs.length?decs.map(x=>'<div class="decision"><b>'+esc(x[0])+'</b><div class="muted">'+esc(x[1])+'</div></div>').join(''):'<div class="muted">Отдельных решений не требуется.</div>')+'</section><section class="section"><h2>Ожидаемый эффект</h2><div class="roi"><div>Экономия времени<br><strong>'+num(roi.total_annual_hours)+'</strong><br><small>часов в год</small></div><div>Экономический эффект<br><strong>'+money(roi.total_annual_saving_kzt)+'</strong><br><small>в год</small></div></div></section><section class="section"><h2>Подразделения, требующие внимания</h2>'+(deps.length?deps.map(x=>'<div class="row"><span>'+esc(x.name)+'</span><b class="'+tone(x.score)+'">'+num(x.score)+'</b></div>').join(''):'<div class="muted">Существенных отклонений по подразделениям не выявлено.</div>')+'</section></div></div>';$('#content').innerHTML=h;$('#updated').textContent='Данные обновлены: '+new Date(d.generated_at||Date.now()).toLocaleString('ru-RU')}
async function getLatest(){const r=await fetch('/executive-intelligence/latest',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Ошибка загрузки');render(d)}
async function refresh(){const b=$('#refresh');b.disabled=true;b.textContent='Обновление…';try{const r=await fetch('/executive-intelligence/collect',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Ошибка обновления');render(d)}catch(e){$('#banner').textContent='Не удалось обновить данные. Показана последняя готовая сводка.';await getLatest()}finally{b.disabled=false;b.textContent='Обновить данные'}}
$('#refresh').onclick=refresh;$('#generate').onclick=async()=>{try{$('#generate').disabled=true;$('#reportStatus').textContent='Формируется подробный отчёт…';const r=await fetch('/management-reports/generate?mode=detailed',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Ошибка генерации');$('#reportStatus').textContent='Отчёт готов.';window.open('/management-reports/'+d.id+'/pdf','_blank')}catch(e){$('#reportStatus').textContent='Подробный отчёт недоступен: '+e.message}finally{$('#generate').disabled=false}};
getLatest().then(()=>{const age=Date.now()-new Date($('#updated').textContent.replace('Данные обновлены: ','')).getTime();if(!Number.isNaN(age)&&age>15*60*1000)refresh()}).catch(refresh);setInterval(getLatest,300000);
</script></body></html>"""
'''


def main() -> None:
    DASH_PATH.write_text(DASHBOARD, encoding='utf-8')
    for path in (APP_PATH, ADMIN_PATH, EXEC_PATH, REF_PATH):
        text = path.read_text(encoding='utf-8').replace('2.0.0-alpha.5', '2.0.0-alpha.6')
        path.write_text(text, encoding='utf-8')
    print('Applied AI-BIT Resilient Executive Brief 2.0.0-alpha.6')


if __name__ == '__main__':
    main()
