from __future__ import annotations


def executive_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT — Executive Dashboard</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff;--purple:#aa8cff}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#07101d,#0b1423);color:var(--text)}a{color:var(--accent);text-decoration:none}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#07101df2;z-index:5}h1,h2,h3{margin:0}.muted{color:var(--muted)}main{padding:24px 28px;max-width:1900px;margin:auto}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.card{background:#101b2df5;border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:34px;font-weight:800;margin-top:8px}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}.accent{color:var(--accent)}.two{display:grid;grid-template-columns:1.1fr .9fr;gap:16px;margin-top:18px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:18px}.risk{padding:14px;border-left:3px solid var(--bad);background:#121f34;border-radius:9px;margin:10px 0}.action{padding:14px;border-left:3px solid var(--accent);background:#121f34;border-radius:9px;margin:10px 0}.chat{display:flex;flex-direction:column;min-height:480px}.messages{flex:1;overflow:auto;max-height:560px;padding-right:6px}.msg{padding:13px 15px;border-radius:12px;margin:10px 0;white-space:pre-wrap}.user{background:#172640;margin-left:12%}.ai{background:#0d192a;margin-right:8%;border:1px solid var(--line)}textarea{width:100%;min-height:88px;resize:vertical;background:#0b1626;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:12px}button{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px 14px;cursor:pointer}button.primary{background:#2459a8;border-color:#3c75cd}button:disabled{opacity:.55;cursor:wait}.quick{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.delta{font-weight:700}.up{color:var(--bad)}.down{color:var(--ok)}.stable{color:var(--warn)}#status{text-align:right;min-height:18px;margin-top:5px}@media(max-width:1200px){.grid{grid-template-columns:repeat(3,1fr)}.two,.three{grid-template-columns:1fr}}@media(max-width:650px){header,main{padding:15px}.grid{grid-template-columns:1fr}}
</style></head><body><header><div><h1>AI-BIT — Executive Dashboard</h1><div class="muted">1.0.0-beta.1 · что происходит, почему и что делать</div></div><div><a href="/dashboard">Аудит</a> · <a href="/operations">Операции</a> <button id="refresh">Обновить</button><div id="status" class="muted"></div></div></header><main>
<div class="grid"><div class="card"><div class="muted">Зрелость внедрения</div><div id="score" class="metric accent">—</div></div><div class="card"><div class="muted">Открытые задачи</div><div id="open" class="metric">—</div></div><div class="card"><div class="muted">Просрочено</div><div id="overdue" class="metric bad">—</div></div><div class="card"><div class="muted">Без срока</div><div id="nodeadline" class="metric warn">—</div></div><div class="card"><div class="muted">В зоне риска</div><div id="risk" class="metric bad">—</div></div><div class="card"><div class="muted">Тренд 30 дней</div><div id="trend" class="metric">—</div></div></div>
<div class="two"><section class="card"><h3>Главные управленческие риски</h3><div id="risks"></div></section><section class="card"><h3>Приоритетные действия</h3><div id="actions"></div></section></div>
<div class="two"><section class="card"><h3>Динамика</h3><div id="trendDetails"></div></section><section class="card chat"><h3>AI Coach · Groq</h3><div class="muted">Задавай вопросы по текущему аудиту и операционным данным.</div><div class="quick"><button data-q="Назови пять главных управленческих рисков и предложи конкретные действия">Главные риски</button><button data-q="Сформируй план улучшений на 30 дней">План на 30 дней</button><button data-q="Какие процессы стоит автоматизировать в первую очередь">Что автоматизировать</button></div><div id="messages" class="messages"><div class="msg ai">Готов анализировать фактические данные портала.</div></div><textarea id="question" placeholder="Например: почему 20% задач просрочены и что изменить в процессе?"></textarea><div style="display:flex;justify-content:flex-end;margin-top:10px"><button id="ask" class="primary">Спросить Groq</button></div></section></div>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function getJSON(url,opt){const sep=url.includes('?')?'&':'?';const r=await fetch(url+sep+'_='+Date.now(),{cache:'no-store',...(opt||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
function deltaLine(label,v,suffix=''){const cls=v>0?'up':v<0?'down':'stable';const sign=v>0?'+':'';return `<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><span>${esc(label)}</span><b class="delta ${cls}">${sign}${v}${suffix}</b></div>`}
async function load(){const [op,ass,tr]=await Promise.all([getJSON('/operations/latest'),getJSON('/crawl/assessment/latest'),getJSON('/operations/trends?days=30')]);const s=op.summary||{};$('#score').textContent=(ass.implementation_score??0)+'%';$('#open').textContent=s.open??0;$('#overdue').textContent=`${s.overdue??0} (${s.overdue_rate??0}%)`;$('#nodeadline').textContent=s.without_deadline??0;$('#risk').textContent=s.employees_at_risk??0;$('#trend').textContent=tr.direction||'—';$('#trend').className='metric '+(tr.direction==='improving'?'ok':tr.direction==='worsening'?'bad':'warn');const recs=op.recommendations||[];$('#risks').innerHTML=recs.slice(0,6).map(r=>`<div class="risk"><b>${esc(r.title)}</b><p>${esc(r.finding)}</p></div>`).join('')||'<div class="muted">Критичных рисков не выявлено</div>';$('#actions').innerHTML=recs.slice(0,6).map(r=>`<div class="action"><b>${esc(r.title)}</b><p>${esc(r.action)}</p></div>`).join('')||'<div class="muted">Приоритетных действий нет</div>';const d=tr.deltas||{};$('#trendDetails').innerHTML=`<div class="muted">Фактический интервал: ${tr.actual_comparison_days??0} дн. · snapshots: ${tr.available_snapshots??0}</div>${deltaLine('Открытые задачи',d.open??0)}${deltaLine('Просроченные',d.overdue??0)}${deltaLine('Доля просрочки',d.overdue_rate??0,'%')}${deltaLine('Без срока',d.without_deadline??0)}${deltaLine('Закрытые',d.completed??0)}${deltaLine('Сотрудники в риске',d.employees_at_risk??0)}`;$('#status').textContent='Обновлено: '+new Date().toLocaleString()}
function add(role,text){const el=document.createElement('div');el.className='msg '+role;el.textContent=text;$('#messages').appendChild(el);$('#messages').scrollTop=$('#messages').scrollHeight}
async function ask(){const q=$('#question').value.trim();if(!q)return;add('user',q);$('#question').value='';const b=$('#ask');b.disabled=true;b.textContent='Анализирую…';try{const d=await getJSON('/ai/advice?question='+encodeURIComponent(q),{method:'POST'});const r=d.result||{};const text=[r.summary,(r.findings||[]).length?'\nФакты:\n• '+r.findings.join('\n• '):'',(r.actions||[]).length?'\nДействия:\n• '+r.actions.join('\n• '):'',(r.risks||[]).length?'\nРиски:\n• '+r.risks.join('\n• '):'',r.expected_effect?'\nОжидаемый эффект:\n'+(Array.isArray(r.expected_effect)?'• '+r.expected_effect.join('\n• '):r.expected_effect):''].join('');add('ai',text||'Ответ пустой')}catch(e){add('ai','Ошибка: '+e.message)}finally{b.disabled=false;b.textContent='Спросить Groq'}}
$('#ask').addEventListener('click',ask);$('#question').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')ask()});document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{$('#question').value=b.dataset.q;ask()}));$('#refresh').addEventListener('click',()=>load().catch(e=>$('#status').textContent='Ошибка: '+e.message));load().catch(e=>$('#status').textContent='Ошибка загрузки: '+e.message)
</script></body></html>'''
