from __future__ import annotations


def management_report_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Отчёт для руководства</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--accent:#6d8cff;--ok:#35d08a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,rgba(109,140,255,.14),transparent 30%),var(--bg);color:var(--text);font:14px/1.5 Inter,Segoe UI,Arial,sans-serif}main{max-width:1200px;margin:auto;padding:28px 28px 80px}.hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.hero h1{margin:0;font-size:28px}.hero p{color:var(--muted);max-width:760px}.actions{display:flex;gap:8px;flex-wrap:wrap}button,a.btn{border:1px solid var(--line);background:var(--panel);color:var(--text);padding:10px 13px;border-radius:10px;cursor:pointer;text-decoration:none}button.primary{background:linear-gradient(135deg,#496ee8,#7657de);border:0}.modes{display:flex;gap:8px;margin:18px 0}.mode.active{border-color:var(--accent);background:rgba(109,140,255,.15)}.status{padding:14px;border:1px solid var(--line);border-radius:12px;background:rgba(16,27,45,.75);color:var(--muted);margin-bottom:18px}.report{display:none;background:#fff;color:#172033;border-radius:16px;padding:32px;box-shadow:0 20px 60px rgba(0,0,0,.3)}.report.show{display:block}.report h2{color:#22335b;margin-top:26px}.report .lead{background:#f4f7ff;border-left:5px solid #5876e8;padding:16px;border-radius:8px;font-size:16px}.report li{margin:6px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{padding:15px;border:1px solid #dce3f0;border-radius:10px;background:#f8faff}.history{margin-top:24px}.history table{width:100%;border-collapse:collapse;background:rgba(16,27,45,.7);border:1px solid var(--line);border-radius:12px;overflow:hidden}.history th,.history td{padding:12px;border-bottom:1px solid var(--line);text-align:left}.muted{color:var(--muted)}@media(max-width:760px){main{padding:18px}.hero{display:block}.grid{grid-template-columns:1fr}.report{padding:20px}}
</style></head><body><main><div class="hero"><div><h1>Отчёт для руководства</h1><p>Понятное управленческое заключение без технического жаргона. Groq анализирует все актуальные данные AI-BIT и формирует выводы, риски и план действий.</p></div><div class="actions"><button id="copy">Скопировать текст</button><a class="btn" id="html" target="_blank">Открыть HTML</a><a class="btn" id="pdf">Скачать PDF</a></div></div>
<div class="modes"><button class="mode active" data-mode="short">Краткий отчёт</button><button class="mode" data-mode="detailed">Подробный отчёт</button><button class="primary" id="generate">Сформировать новый отчёт</button></div><div class="status" id="status">Выберите режим и сформируйте отчёт.</div><article class="report" id="report"></article>
<section class="history"><h2>История отчётов</h2><table><thead><tr><th>Дата</th><th>Режим</th><th>Отчёт</th></tr></thead><tbody id="history"></tbody></table></section></main><script>
let mode='short', current=null;const $=s=>document.querySelector(s);document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});function list(x){return x&&x.length?'<ul>'+x.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul>':'<p>Значимых пунктов не выявлено.</p>'}function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}function render(d){const s=d.sections||{},names={administration:'Администрирование и управление системой',task_management:'Организация работы и контроль задач',business_processes:'Бизнес-процессы',sales_crm:'Продажи и работа с клиентами',document_flow:'Документооборот',automation:'Автоматизация'};let html='<h2>Общая оценка</h2><div class="lead">'+esc(d.overall_assessment)+'</div><div class="grid"><div class="card"><h2>Что работает хорошо</h2>'+list(d.strengths)+'</div><div class="card"><h2>Основные слабые места</h2>'+list(d.weaknesses)+'</div></div>';for(const [k,n] of Object.entries(names)){const v=s[k]||{};html+='<h2>'+n+'</h2><p>'+esc(v.assessment||'Данных недостаточно.')+'</p><h3>Что рекомендуется</h3>'+list(v.recommendations)}html+='<h2>Главные риски</h2>'+list(d.main_risks)+'<h2>Что сделать в первую очередь</h2>'+list(d.top_priorities);const p=d.plan||{};html+='<h2>План на 30 / 60 / 90 дней</h2><h3>30 дней</h3>'+list(p['30_days'])+'<h3>60 дней</h3>'+list(p['60_days'])+'<h3>90 дней</h3>'+list(p['90_days'])+'<h2>Итог для руководства</h2><div class="lead">'+esc(d.conclusion)+'</div>';$('#report').innerHTML=html;$('#report').classList.add('show')}
async function load(id){const r=await fetch('/management-reports/'+id+'/json');if(!r.ok)throw new Error('Не удалось открыть отчёт');current=await r.json();render(current);$('#html').href='/management-reports/'+id+'/html';$('#pdf').href='/management-reports/'+id+'/pdf';$('#status').textContent='Отчёт сформирован: '+(current.generated_at||'')}
async function history(){const r=await fetch('/management-reports');const rows=await r.json();$('#history').innerHTML=rows.length?rows.map(x=>'<tr><td>'+esc(x.generated_at||'')+'</td><td>'+(x.mode==='detailed'?'Подробный':'Краткий')+'</td><td><button onclick="load(\''+x.id+'\')">Открыть</button></td></tr>').join(''):'<tr><td colspan="3" class="muted">Отчёты ещё не формировались.</td></tr>'}
$('#generate').onclick=async()=>{try{$('#generate').disabled=true;$('#status').textContent='Groq анализирует данные и формирует понятный отчёт…';const r=await fetch('/management-reports/generate?mode='+mode,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Ошибка генерации');await load(d.id);await history()}catch(e){$('#status').textContent='Ошибка: '+e.message}finally{$('#generate').disabled=false}};$('#copy').onclick=async()=>{if(!current)return;await navigator.clipboard.writeText($('#report').innerText);$('#status').textContent='Текст отчёта скопирован.'};history();
</script></body></html>'''
