from __future__ import annotations


def operations_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT — Operational Intelligence</title><style>
:root{color-scheme:dark;--bg:#08101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff}*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#08101d,#0c1424);color:var(--text)}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#08101df2;z-index:3}h1,h2,h3{margin:0}a{color:var(--accent);text-decoration:none}button,select{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 12px;cursor:pointer}button:disabled{opacity:.6}main{padding:24px 28px;max-width:1800px;margin:auto}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.card{background:#101b2df5;border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:30px;font-weight:750;margin-top:8px}.muted{color:var(--muted)}.bad,.worsening{color:var(--bad)}.warn,.stable{color:var(--warn)}.ok,.improving{color:var(--ok)}section{margin-top:18px}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tab.active,.period.active{border-color:var(--accent)}.view{display:none}.view.active{display:block}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted)}.scroll{overflow:auto;max-height:680px}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.critical,.high{color:var(--bad)}.medium{color:var(--warn)}.low{color:var(--ok)}.rec{padding:14px;border-left:3px solid var(--warn);background:#121f34;border-radius:8px;margin:10px 0}.rec.high{border-color:var(--bad)}.delta{font-size:22px;font-weight:700}.periods{display:flex;gap:8px;margin:12px 0}.bar{height:9px;background:#202f49;border-radius:8px;overflow:hidden}.bar span{display:block;height:100%;background:linear-gradient(90deg,var(--accent),#aa8cff)}#status{text-align:right;min-height:18px;margin-top:5px}@media(max-width:1200px){.grid{grid-template-columns:repeat(3,1fr)}.two,.three{grid-template-columns:1fr}}@media(max-width:650px){header,main{padding:16px}.grid{grid-template-columns:1fr}}
</style></head><body><header><div><h1>AI-BIT — Operational Intelligence</h1><div class="muted">1.0.0-alpha.2: нагрузка, риски и динамика 7 / 30 / 90 дней</div></div><div><a href="/dashboard">← Аудит внедрения</a> <button id="collect">Собрать данные</button><div id="status" class="muted"></div></div></header><main>
<div class="grid"><div class="card"><div class="muted">Сотрудники</div><div id="users" class="metric">—</div></div><div class="card"><div class="muted">Открытые задачи</div><div id="open" class="metric">—</div></div><div class="card"><div class="muted">Просрочено</div><div id="overdue" class="metric bad">—</div></div><div class="card"><div class="muted">Без срока</div><div id="nodeadline" class="metric warn">—</div></div><div class="card"><div class="muted">Закрыто</div><div id="completed" class="metric ok">—</div></div><div class="card"><div class="muted">В зоне риска</div><div id="risk" class="metric bad">—</div></div></div>
<div class="tabs"><button class="tab active" data-view="overview">Обзор</button><button class="tab" data-view="trends">Динамика</button><button class="tab" data-view="employees">Сотрудники</button><button class="tab" data-view="departments">Подразделения</button><button class="tab" data-view="recommendations">Рекомендации</button></div>
<div id="overview" class="view active"><section class="two"><div class="card"><h3>Главные риски</h3><div id="topRisks"></div></div><div class="card"><h3>Методика</h3><p id="methodology" class="muted"></p><p>Показатели не являются рейтингом ценности сотрудников. Они выявляют перегрузку, просрочку и проблемы планирования.</p></div></section></div>
<div id="trends" class="view"><section class="card"><h3>Динамика показателей</h3><div class="periods"><button class="period" data-days="7">7 дней</button><button class="period active" data-days="30">30 дней</button><button class="period" data-days="90">90 дней</button></div><div id="trendStatus" class="muted"></div><div class="grid" style="margin-top:14px"><div class="card"><div class="muted">Открытые</div><div id="dOpen" class="delta">—</div></div><div class="card"><div class="muted">Просроченные</div><div id="dOverdue" class="delta">—</div></div><div class="card"><div class="muted">Доля просрочки</div><div id="dRate" class="delta">—</div></div><div class="card"><div class="muted">Без срока</div><div id="dNoDeadline" class="delta">—</div></div><div class="card"><div class="muted">Закрытые</div><div id="dCompleted" class="delta">—</div></div><div class="card"><div class="muted">Сотрудники в риске</div><div id="dRisk" class="delta">—</div></div></div></section><section class="two"><div class="card"><h3>Ухудшение</h3><div id="worsened"></div></div><div class="card"><h3>Улучшение</h3><div id="improved"></div></div></section><section class="two"><div class="card"><h3>Вошли в зону риска</h3><div id="enteredRisk"></div></div><div class="card"><h3>Вышли из зоны риска</h3><div id="exitedRisk"></div></div></section></div>
<div id="employees" class="view"><section class="card"><h3>Аналитика сотрудников</h3><div class="scroll"><table><thead><tr><th>Сотрудник</th><th>Подразделение</th><th>Открыто</th><th>Просрочено</th><th>Без срока</th><th>Закрыто</th><th>Среднее закрытие</th><th>Риск</th></tr></thead><tbody id="employeeRows"></tbody></table></div></section></div>
<div id="departments" class="view"><section class="card"><h3>Аналитика подразделений</h3><div class="scroll"><table><thead><tr><th>Подразделение</th><th>Сотрудников</th><th>Открыто</th><th>Просрочено</th><th>Доля просрочки</th><th>Без срока</th><th>Закрыто</th><th>Риск</th></tr></thead><tbody id="departmentRows"></tbody></table></div></section></div>
<div id="recommendations" class="view"><section class="card"><h3>Управленческие рекомендации</h3><div id="recommendationRows"></div></section></div>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function json(url,opt){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',...(opt||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
function signed(v,suffix=''){const n=Number(v||0);const cls=n>0?'bad':n<0?'ok':'warn';return `<span class="${cls}">${n>0?'+':''}${n}${suffix}</span>`}
function movement(rows){return (rows||[]).map(x=>`<div class="rec ${x.overdue_rate_delta>0?'high':''}"><b>${esc(x.name)}</b><div>Просрочка: ${signed(x.overdue_delta)} · доля: ${signed(x.overdue_rate_delta,'%')} · без срока: ${signed(x.without_deadline_delta)}</div><div class="muted">Риск: ${esc(x.risk_before)} → ${esc(x.risk_after)}</div></div>`).join('')||'<div class="muted">Нет изменений</div>'}
function render(d){const s=d.summary||{};$('#users').textContent=s.active_users??0;$('#open').textContent=s.open??0;$('#overdue').textContent=`${s.overdue??0} (${s.overdue_rate??0}%)`;$('#nodeadline').textContent=s.without_deadline??0;$('#completed').textContent=s.completed??0;$('#risk').textContent=s.employees_at_risk??0;$('#methodology').textContent=d.methodology||'';$('#employeeRows').innerHTML=(d.employees||[]).map(x=>`<tr><td><b>${esc(x.name)}</b><div class="muted">${esc(x.email||'')}</div></td><td>${esc((x.departments||[]).join(', ')||'—')}</td><td>${x.open_tasks}</td><td class="bad">${x.overdue_tasks} (${x.overdue_rate}%)</td><td class="warn">${x.without_deadline}</td><td>${x.completed_tasks}</td><td>${x.avg_completion_days==null?'—':x.avg_completion_days+' дн.'}</td><td><span class="pill ${esc(x.risk)}">${esc(x.risk)} · ${x.risk_score}</span></td></tr>`).join('');$('#departmentRows').innerHTML=(d.departments||[]).map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.employees}</td><td>${x.open}</td><td class="bad">${x.overdue}</td><td>${x.overdue_rate}%</td><td class="warn">${x.without_deadline}</td><td>${x.completed}</td><td><span class="pill ${esc(x.risk)}">${esc(x.risk)}</span></td></tr>`).join('');const recs=d.recommendations||[];$('#recommendationRows').innerHTML=recs.map(r=>`<div class="rec ${esc(r.severity)}"><b>${esc(r.title)}</b><p>${esc(r.finding)}</p><div class="muted">Что делать: ${esc(r.action)}</div></div>`).join('')||'<div class="muted">Критичных рекомендаций нет</div>';$('#topRisks').innerHTML=(d.employees||[]).filter(x=>['critical','high'].includes(x.risk)).slice(0,10).map(x=>`<div class="rec high"><b>${esc(x.name)}</b><div>${x.open_tasks} открытых, ${x.overdue_tasks} просроченных, ${x.without_deadline} без срока</div></div>`).join('')||'<div class="muted">Высоких рисков не выявлено</div>';$('#status').textContent='Обновлено: '+new Date(d.generated_at).toLocaleString()}
function renderTrends(t){$('#trendStatus').innerHTML=t.status==='ok'?`Направление: <b class="${esc(t.direction)}">${esc(t.direction)}</b> · фактический интервал ${t.actual_comparison_days??0} дн. · snapshot'ов ${t.available_snapshots}`:esc(t.message||'Недостаточно истории');const d=t.deltas||{};$('#dOpen').innerHTML=signed(d.open);$('#dOverdue').innerHTML=signed(d.overdue);$('#dRate').innerHTML=signed(d.overdue_rate,'%');$('#dNoDeadline').innerHTML=signed(d.without_deadline);$('#dCompleted').innerHTML=signed(d.completed);$('#dRisk').innerHTML=signed(d.employees_at_risk);$('#worsened').innerHTML=movement([...(t.departments?.worsened||[]),...(t.employees?.worsened||[])].slice(0,15));$('#improved').innerHTML=movement([...(t.departments?.improved||[]),...(t.employees?.improved||[])].slice(0,15));$('#enteredRisk').innerHTML=movement(t.employees?.entered_risk||[]);$('#exitedRisk').innerHTML=movement(t.employees?.exited_risk||[])}
async function loadTrends(days=30){try{renderTrends(await json('/operations/trends?days='+days))}catch(e){$('#trendStatus').textContent='Ошибка трендов: '+e.message}}
async function load(){render(await json('/operations/latest'));await loadTrends(30)}$('#collect').addEventListener('click',async()=>{const b=$('#collect');b.disabled=true;b.textContent='Сбор…';$('#status').textContent='Получаю данные из Bitrix24…';try{render(await json('/operations/collect',{method:'POST'}));await loadTrends(Number(document.querySelector('.period.active')?.dataset.days||30))}catch(e){$('#status').textContent='Ошибка: '+e.message}finally{b.disabled=false;b.textContent='Собрать данные'}});$('.tabs').addEventListener('click',e=>{if(!e.target.dataset.view)return;document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.view).classList.add('active')});document.querySelector('.periods').addEventListener('click',e=>{if(!e.target.dataset.days)return;document.querySelectorAll('.period').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');loadTrends(Number(e.target.dataset.days))});load().catch(e=>$('#status').textContent='Сначала нажмите «Собрать данные»: '+e.message)
</script></body></html>'''
