from __future__ import annotations


def process_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT — Process Mining</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff}*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#07101d,#0b1423);color:var(--text)}a{color:var(--accent);text-decoration:none}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#07101df2;z-index:5}h1,h2,h3{margin:0}.muted{color:var(--muted)}main{padding:24px 28px;max-width:1900px;margin:auto}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.card{background:#101b2df5;border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:30px;font-weight:800;margin-top:8px}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}button{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 12px;cursor:pointer}.tab.active{border-color:var(--accent)}.view{display:none}.view.active{display:block}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted)}.scroll{overflow:auto;max-height:700px}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.high{color:var(--bad)}.medium{color:var(--warn)}.low{color:var(--ok)}.rec{padding:14px;border-left:3px solid var(--accent);background:#121f34;border-radius:8px;margin:10px 0}#status{text-align:right;min-height:18px}@media(max-width:1200px){.grid{grid-template-columns:repeat(3,1fr)}.two{grid-template-columns:1fr}}@media(max-width:650px){header,main{padding:15px}.grid{grid-template-columns:1fr}}
</style></head><body><header><div><h1>AI-BIT — Process Mining</h1><div class="muted">1.0.0-beta.2 · повторяющиеся процессы, маршруты и кандидаты на автоматизацию</div></div><div><a href="/executive">Executive</a> · <a href="/operations">Операции</a> <button id="refresh">Обновить</button><div id="status" class="muted"></div></div></header><main>
<div class="grid"><div class="card"><div class="muted">Задач проанализировано</div><div id="tasks" class="metric">—</div></div><div class="card"><div class="muted">Повторяющихся паттернов</div><div id="patterns" class="metric">—</div></div><div class="card"><div class="muted">Кандидатов на автоматизацию</div><div id="candidates" class="metric">—</div></div><div class="card"><div class="muted">Маршрутов передачи</div><div id="routes" class="metric">—</div></div><div class="card"><div class="muted">Узких мест</div><div id="bottlenecks" class="metric">—</div></div><div class="card"><div class="muted">Оценка ручного времени</div><div id="hours" class="metric">—</div></div></div>
<div class="tabs"><button class="tab active" data-view="automation">Автоматизация</button><button class="tab" data-view="flows">Маршруты</button><button class="tab" data-view="bottle">Узкие места</button><button class="tab" data-view="method">Методика</button></div>
<div id="automation" class="view active"><section class="card"><h3>Кандидаты на автоматизацию</h3><div class="scroll"><table><thead><tr><th>Паттерн</th><th>Количество</th><th>Проблемы</th><th>Участники</th><th>Score</th><th>Рекомендация</th></tr></thead><tbody id="automationRows"></tbody></table></div></section></div>
<div id="flows" class="view"><section class="card"><h3>Повторяющиеся маршруты постановщик → исполнитель</h3><div id="flowRows"></div></section></div>
<div id="bottle" class="view"><section class="card"><h3>Потенциальные ручные диспетчерские узлы</h3><div id="bottleneckRows"></div></section></div>
<div id="method" class="view"><section class="card"><h3>Методика</h3><p id="methodology" class="muted"></p><p>Расчёт времени является ориентиром для приоритизации. Перед внедрением автоматизации владелец процесса должен подтвердить частоту, сложность и экономический эффект.</p></section></div>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function json(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function render(d){const s=d.summary||{};$('#tasks').textContent=s.tasks_analyzed??0;$('#patterns').textContent=s.repeated_patterns??0;$('#candidates').textContent=s.automation_candidates??0;$('#routes').textContent=s.handoff_routes??0;$('#bottlenecks').textContent=s.potential_bottlenecks??0;$('#hours').textContent=(s.estimated_manual_hours??0)+' ч.';$('#methodology').textContent=d.methodology||'';$('#automationRows').innerHTML=(d.automation_candidates||[]).map(x=>`<tr><td><b>${esc(x.sample_title)}</b><div class="muted">${esc(x.pattern)}</div></td><td>${x.count}</td><td>${x.overdue} просрочено<br>${x.without_deadline} без срока</td><td>Ставит: ${esc(x.top_creator)}<br>Исполняет: ${esc(x.top_responsible)}</td><td><span class="pill ${x.automation_score>=70?'high':x.automation_score>=45?'medium':'low'}">${x.automation_score}</span></td><td>${esc(x.recommendation)}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Повторяющиеся паттерны не обнаружены</td></tr>';$('#flowRows').innerHTML=(d.handoff_routes||[]).map(x=>`<div class="rec"><b>${esc(x.creator)} → ${esc(x.responsible)}</b><div>${x.tasks} задач</div><div class="muted">${esc(x.recommendation)}</div></div>`).join('')||'<div class="muted">Повторяющиеся маршруты не обнаружены</div>';$('#bottleneckRows').innerHTML=(d.bottlenecks||[]).map(x=>`<div class="rec"><b>${esc(x.name)}</b><div>Создано: ${x.created_tasks} · открыто: ${x.open_tasks} · просрочено: ${x.overdue_tasks}</div><div class="muted">${esc(x.finding)} ${esc(x.recommendation)}</div></div>`).join('')||'<div class="muted">Явных узких мест не обнаружено</div>';$('#status').textContent='Обновлено: '+new Date(d.generated_at).toLocaleString()}
async function load(){render(await json('/process-mining/latest'))}$('.tabs').addEventListener('click',e=>{if(!e.target.dataset.view)return;document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.view).classList.add('active')});$('#refresh').addEventListener('click',()=>load().catch(e=>$('#status').textContent='Ошибка: '+e.message));load().catch(e=>$('#status').textContent='Сначала соберите новый operational snapshot: '+e.message)
</script></body></html>'''
