from __future__ import annotations


def reports_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT Enterprise — Reports</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--accent:#6c7cff;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#07101d,#0b1423);color:var(--text)}header{padding:22px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;background:#07101df5;position:sticky;top:0;z-index:3}h1,h2,h3{margin:0}.muted{color:var(--muted)}button,a.btn{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px 14px;cursor:pointer;text-decoration:none;display:inline-block}button.primary{background:linear-gradient(135deg,#536dff,#7f5cff);border-color:#7f8dff}button:disabled{opacity:.55;cursor:wait}main{padding:24px 28px;max-width:1700px;margin:auto}.grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.card{background:#101b2df2;border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 18px 45px #0003}.metric{font-size:32px;font-weight:800;margin-top:8px}.actions{display:flex;gap:8px;flex-wrap:wrap}.report{display:grid;grid-template-columns:1.4fr repeat(3,auto);gap:12px;align-items:center;padding:14px;border-bottom:1px solid var(--line)}.report:last-child{border-bottom:0}.empty{padding:24px;text-align:center;color:var(--muted)}#status{margin-top:6px;text-align:right;min-height:18px}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}.report{grid-template-columns:1fr}.actions{justify-content:flex-start}}@media(max-width:620px){header{align-items:flex-start;gap:12px;flex-direction:column}main{padding:16px}.grid{grid-template-columns:1fr}}
</style></head><body><header><div><h1>Reports & Export</h1><div class="muted">1.0.0-rc.5 · управленческие отчёты HTML / JSON / PDF</div></div><div><button id="generate" class="primary">Сформировать отчёт</button><div id="status" class="muted"></div></div></header><main>
<section class="grid"><div class="card"><div class="muted">Enterprise Health</div><div id="health" class="metric">—</div></div><div class="card"><div class="muted">Зрелость внедрения</div><div id="implementation" class="metric">—</div></div><div class="card"><div class="muted">Открытые задачи</div><div id="open" class="metric">—</div></div><div class="card"><div class="muted">Просрочено</div><div id="overdue" class="metric bad">—</div></div><div class="card"><div class="muted">Сотрудники в риске</div><div id="risk" class="metric warn">—</div></div></section>
<section class="card" style="margin-top:18px"><h2>Архив отчётов</h2><div class="muted" style="margin:5px 0 12px">Каждый отчёт формируется по последним доступным данным всех контуров.</div><div id="rows"></div></section>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function json(url,opt){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',...(opt||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
function render(rows){const latest=rows[0]||{};const s=latest.summary||{};$('#health').textContent=(s.enterprise_health??'—')+(s.enterprise_health==null?'':'%');$('#implementation').textContent=(s.implementation_score??'—')+(s.implementation_score==null?'':'%');$('#open').textContent=s.open_tasks??'—';$('#overdue').textContent=s.overdue_tasks??'—';$('#risk').textContent=s.employees_at_risk??'—';$('#rows').innerHTML=(rows||[]).map(r=>`<div class="report"><div><b>${esc(new Date(r.generated_at).toLocaleString())}</b><div class="muted">ID: ${esc(r.id)}</div></div><a class="btn" href="/reports/${encodeURIComponent(r.id)}/html" target="_blank">HTML</a><a class="btn" href="/reports/${encodeURIComponent(r.id)}/json" target="_blank">JSON</a><a class="btn" href="/reports/${encodeURIComponent(r.id)}/pdf" target="_blank">PDF</a></div>`).join('')||'<div class="empty">Отчётов пока нет. Нажмите «Сформировать отчёт».</div>'}
async function load(){render(await json('/reports'))}$('#generate').addEventListener('click',async()=>{const b=$('#generate');b.disabled=true;b.textContent='Формирование…';$('#status').textContent='Собираю данные и создаю PDF…';try{await json('/reports/generate',{method:'POST'});await load();$('#status').textContent='Отчёт готов'}catch(e){$('#status').textContent='Ошибка: '+e.message}finally{b.disabled=false;b.textContent='Сформировать отчёт'}});load().catch(e=>$('#status').textContent='Ошибка загрузки: '+e.message)
</script></body></html>'''
