from __future__ import annotations


def system_dashboard_html() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT Enterprise — System Health</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#101b2d;--line:#283956;--text:#eef5ff;--muted:#91a3bd;--ok:#39d98a;--warn:#ffbd59;--bad:#ff617b;--accent:#62a0ff}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--text)}header{padding:20px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}main{padding:24px 28px;max-width:1800px;margin:auto}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.card{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:18px}.metric{font-size:32px;font-weight:800;margin-top:8px}.muted{color:var(--muted)}.ok{color:var(--ok)}.warning,.stale,.missing{color:var(--warn)}.error,.denied{color:var(--bad)}button{background:#172640;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px 14px;cursor:pointer}.row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)}.pill{padding:4px 9px;border-radius:999px;background:#21314c;font-size:12px}.rec{padding:14px;border-left:3px solid var(--warn);background:#121f34;border-radius:9px;margin:10px 0}.rec.high{border-color:var(--bad)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted)}@media(max-width:1100px){.grid,.two{grid-template-columns:1fr 1fr}}@media(max-width:650px){header,main{padding:15px}.grid,.two{grid-template-columns:1fr}}
</style></head><body><header><div><h1>AI-BIT Enterprise — System Health</h1><div class="muted">1.0.0-rc.3 · источники данных, свежесть и права</div></div><div><button id="refresh">Обновить диагностику</button><div id="status" class="muted"></div></div></header><main>
<div class="grid"><div class="card"><div class="muted">Общий статус</div><div id="overall" class="metric">—</div></div><div class="card"><div class="muted">Сервисы</div><div id="services" class="metric">—</div></div><div class="card"><div class="muted">Актуальные данные</div><div id="fresh" class="metric">—</div></div><div class="card"><div class="muted">Недоступные источники</div><div id="denied" class="metric">—</div></div></div>
<div class="two"><section class="card"><h3>Сервисы</h3><div id="checks"></div></section><section class="card"><h3>Свежесть данных</h3><div id="freshness"></div></section></div>
<div class="two"><section class="card"><h3>Качество данных</h3><div id="quality"></div></section><section class="card"><h3>Рекомендации</h3><div id="recommendations"></div></section></div>
<section class="card" style="margin-top:18px"><h3>Права и REST-источники</h3><div style="overflow:auto;max-height:520px"><table><thead><tr><th>Контур</th><th>Метод</th><th>Статус</th><th>Ошибка</th></tr></thead><tbody id="rights"></tbody></table></div></section>
</main><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function json(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function row(name,status,message,extra=''){return `<div class="row"><div><b>${esc(name)}</b><div class="muted">${esc(message||'')}${extra}</div></div><span class="pill ${esc(status)}">${esc(status)}</span></div>`}
function render(d){const s=d.summary||{};$('#overall').textContent=d.overall_status;$('#overall').className='metric '+d.overall_status;$('#services').textContent=`${s.services_ok??0}/${s.services_total??0}`;$('#fresh').textContent=`${s.fresh_datasets??0}/${s.datasets_total??0}`;$('#denied').textContent=s.denied_sources??0;$('#denied').className='metric '+((s.denied_sources??0)>0?'error':'ok');$('#checks').innerHTML=(d.checks||[]).map(x=>row(x.name,x.status,x.message,x.model?` · ${esc(x.model)}`:'')).join('');$('#freshness').innerHTML=(d.freshness||[]).map(x=>row(x.name,x.status,x.age_hours==null?x.message:`${x.message} · ${x.age_hours} ч.`)).join('');const q=d.data_quality||{};$('#quality').innerHTML=Object.entries(q).map(([k,v])=>`<div class="row"><span>${esc(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('');$('#recommendations').innerHTML=(d.recommendations||[]).map(r=>`<div class="rec ${esc(r.severity)}"><b>${esc(r.title)}</b><div class="muted">${esc(r.action)}</div></div>`).join('')||'<div class="muted">Критичных рекомендаций нет</div>';$('#rights').innerHTML=(d.rights||[]).map(x=>`<tr><td>${esc(x.domain)}</td><td>${esc(x.method)}</td><td class="${esc(x.status)}">${esc(x.status)}</td><td>${esc(x.error||'')}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">Данные о правах ещё не собраны</td></tr>';$('#status').textContent='Проверено: '+new Date(d.generated_at).toLocaleString()}
async function load(){render(await json('/system/health'))}$('#refresh').addEventListener('click',()=>load().catch(e=>$('#status').textContent='Ошибка: '+e.message));load().catch(e=>$('#status').textContent='Ошибка загрузки: '+e.message)
</script></body></html>'''
