from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["infrastructure-ui"])


@router.get("/infrastructure", response_class=HTMLResponse, include_in_schema=False)
def infrastructure() -> str:
    return r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-BIT Infrastructure</title><style>
:root{--bg:#07101d;--panel:#0f1b2d;--line:#243653;--text:#eef4ff;--muted:#8fa3bf;--accent:#6d8cff;--ok:#35d08a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,rgba(109,140,255,.16),transparent 30%),var(--bg);color:var(--text);font:14px/1.45 Inter,Segoe UI,Arial,sans-serif}.shell{max-width:1440px;margin:auto;padding:28px}.head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.head h1{margin:0;font-size:26px}.head p{margin:5px 0 0;color:var(--muted)}select,button{background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px 12px}.cards{display:grid;grid-template-columns:repeat(6,minmax(150px,1fr));gap:12px}.card,.panel{border:1px solid var(--line);background:linear-gradient(180deg,rgba(15,27,45,.96),rgba(10,19,33,.96));border-radius:16px;padding:16px}.card small{color:var(--muted)}.card strong{display:block;font-size:25px;margin-top:7px}.health{color:var(--ok)}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-top:14px}.panel h2{font-size:16px;margin:0 0 13px}.list{display:grid;gap:8px;max-height:610px;overflow:auto}.item{border:1px solid rgba(255,255,255,.07);border-radius:11px;padding:11px;background:rgba(255,255,255,.025)}.item b{display:block}.item span{font-size:12px;color:var(--muted)}.empty{color:var(--muted);padding:30px;text-align:center}@media(max-width:1000px){.cards{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:620px){.shell{padding:14px}.head{display:block}.head div:last-child{margin-top:12px}.cards{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main class="shell"><header class="head"><div><h1>Infrastructure Discovery</h1><p>Фактическая модель инфраструктуры из evidence-снимков</p></div><div><select id="agent"></select> <button id="reload">Обновить</button></div></header><section class="cards"><div class="card"><small>Forest</small><strong id="forest">—</strong></div><div class="card"><small>Домены</small><strong id="domains">0</strong></div><div class="card"><small>Контроллеры</small><strong id="dcs">0</strong></div><div class="card"><small>OU</small><strong id="ous">0</strong></div><div class="card"><small>GPO</small><strong id="gpos">0</strong></div><div class="card"><small>Health score</small><strong class="health" id="health">0%</strong></div></section><section class="grid"><div class="panel"><h2>Объекты инфраструктуры</h2><div class="list" id="nodes"><div class="empty">Снапшоты ещё не загружены</div></div></div><div class="panel"><h2>Связи Knowledge Graph</h2><div class="list" id="edges"><div class="empty">Нет данных</div></div></div></section></main><script>
const $=s=>document.querySelector(s);async function agents(){const r=await fetch('/api/v1/discovery/agents');const a=await r.json();$('#agent').innerHTML=a.length?a.map(x=>`<option value="${x.agent_id}">${x.agent_id} · ${x.collected_at_utc||''}</option>`).join(''):'<option value="">Нет агентов</option>';if(a.length)load(a[0].agent_id)}async function load(id){if(!id)return;const r=await fetch(`/api/v1/discovery/agents/${encodeURIComponent(id)}/graph`);const g=await r.json();const s=g.summary||{};$('#forest').textContent=s.forest||'—';$('#domains').textContent=s.domains||0;$('#dcs').textContent=s.domain_controllers||0;$('#ous').textContent=s.organizational_units||0;$('#gpos').textContent=s.group_policies||0;$('#health').textContent=(s.health_score||0)+'%';$('#nodes').innerHTML=g.nodes.map(n=>`<div class="item"><b>${n.label}</b><span>${n.type}</span></div>`).join('')||'<div class="empty">Нет объектов</div>';$('#edges').innerHTML=g.edges.map(e=>`<div class="item"><b>${e.relation}</b><span>${e.source} → ${e.target}</span></div>`).join('')||'<div class="empty">Нет связей</div>'}$('#agent').addEventListener('change',e=>load(e.target.value));$('#reload').addEventListener('click',agents);agents();
</script></body></html>'''
